### ISSUE TITLE
Action failed with transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by khos2ow** [dawidd6/action-homebrew-bump-formula#17]
I just started using this action and I got this error:

```
==> Fetching homebrew/master
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
Error: Failure while executing; `git fetch homebrew master` exited with 128.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:287:in `safe_system': Failure while executing; `brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\(https://github.com/dawidd6/action-homebrew-bump-formula\) --version=0.10.1 --url=https://github.com/terraform-docs/terraform-docs/archive/v0.10.1.tar.gz terraform-docs` exited with 1. (ErrorDuringExecution)
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.4.1/main.rb:28:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.4.1/main.rb:116:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.4.1/main.rb:17:in `<main>'
Error: Process completed with exit code 1.
```
Full log can be found [here](https://github.com/terraform-docs/terraform-docs/runs/1179210533).

Steps were:

- created a bot account
- forked https://github.com/Homebrew/homebrew-core under its profile
- created a Personal Token and passed it into the action's `token`

Coincidentally I noticed, at the time of this failure, github had an incident and Action has been degraded, so I wasn't able to pinpoint the problem to the GH Action or this action or my setup.

**Comment by khos2ow** [comment]
It turned out it was GitHub Action issue after all! :tada:
