### ISSUE TITLE
Failure while executing; `brew livecheck ...`

### ISSUE THREAD

**Issue by chenrui333** [dawidd6/action-homebrew-bump-formula#19]
```
 [command]git config --global user.name chenrui
 [command]git config --global user.email chenrui333@gmail.com
 [command]brew livecheck --quiet --newer-only --full-name --json
 /usr/local/Homebrew/Library/Homebrew/utils/popen.rb:16:in `safe_popen_read': Failure while executing; `brew livecheck --quiet --newer-only --full-name --json` exited with 1. Here's the output: (ErrorDuringExecution)
 	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:42:in `read_brew'
 	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:134:in `<module:Homebrew>'
 	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
```

**Comment by dawidd6** [comment]
I presume you are trying to livecheck a bunch of node based formulae. Had this issue before, it's related to npmjs registry rate limiting and we need some retrying/backoff mechanism for that in brew.

**Comment by chenrui333** [comment]
Got you!
