### ISSUE TITLE
Unable to fork: Not Found

### ISSUE THREAD

**Issue by kdheepak** [dawidd6/action-homebrew-bump-formula#23]
I'm getting the following error when I run this workflow:

https://github.com/kdheepak/taskwarrior-tui/runs/1569338587#step:2:103

```
git config --global user.name Dheepak Krishnamurthy
git config --global user.email me@kdheepak.com
brew bump-formula-pr --no-audit --no-browse --message=[`action-homebrew-bump-formula`](dawidd6/action-homebrew-bump-formula) --version=0.9.5 --url=v0.9.5.tar.gz taskwarrior-tui
==> Downloading v0.9.5.tar.gz
==> Downloading from codeload.github.com/kdheepak/taskwarrior-tui/tar.gz/v0.9.5
Warning: Cannot verify integrity of '98ec77c25f8c23f3415ef2a68277bcbb262dbb3944eb2d5e33ed304511ab9000--taskwarrior-tui-0.9.5.tar.gz'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "1e31623a1b372c5cfa628fadb45c5c4d6e7bee3ca17959d923f28651ba1040e8"
==> replace /https:\/\/github\.com\/kdheepak\/taskwarrior\-tui\/archive\/v0\.9\.4\.tar\.gz/ with "v0.9.5.tar.gz"
==> replace "ec0d909a666d5d8319f86bf715036635d5ec9899bdb242d1eb3e2cbb4c04d2d2" with "1e31623a1b372c5cfa628fadb45c5c4d6e7bee3ca17959d923f28651ba1040e8"
==> Skipping `brew audit`
Error: Unable to fork: Not Found!
/usr/local/Homebrew/Library/Homebrew/utils.rb:303:in `safe_system': Failure while executing; `brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\(https://github.com/dawidd6/action-homebrew-bump-formula\) --version=0.9.5 --url=v0.9.5.tar.gz taskwarrior-tui` exited with 1. (ErrorDuringExecution)
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:28:in `brew'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:116:in `<module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
Error: Process completed with exit code 1.
```

Any idea what might be going on?

**Comment by dawidd6** [comment]
Maybe you have wrong permissions for the token. It needs `public:repo` scope.

**Comment by kdheepak** [comment]
Thanks! I think that resolved it!
