### ISSUE TITLE
[BUG] Spurious "error: failed to push some refs"

### ISSUE THREAD

**Issue by HorlogeSkynet** [dawidd6/action-homebrew-bump-formula#39]
Hey @dawidd6 ! Firstly, thanks for this awesome action.

I've set up a (both automatic and manual) deployment job using your action [here](https://github.com/HorlogeSkynet/archey4/actions/runs/1200814231/workflow).
It ended up working well, except for a previous run, where it crashed with :

```
Switched to a new branch 'bump-archey4-4.13.1'
M	Formula/archey4.rb
[bump-archey4-4.13.1 8d36629c7c] archey4 4.13.1
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: fatal error in commit_refs        
To HorlogeSkynet/homebrew-core.git
 ! [remote rejected]       bump-archey4-4.13.1 -> bump-archey4-4.13.1 (failure)
error: failed to push some refs to 'HorlogeSkynet/homebrew-core.git'
Error: Failure while executing; `git push --set-upstream https://***@github.com/HorlogeSkynet/homebrew-core.git bump-archey4-4.13.1:bump-archey4-4.13.1` exited with 1.
/usr/local/Homebrew/Library/Homebrew/utils.rb:322:in `safe_system': Failure while executing; `/usr/local/bin/brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\(https://github.com/dawidd6/action-homebrew-bump-formula\) --version=4.13.1 --url=files.pythonhosted.org/packages/54/60/212f5018cc4671fd6b288faf2018ff74e8fcf68703c72e31bcea9ca6217a/archey4-4.13.1.tar.gz archey4` exited with 1. (ErrorDuringExecution)
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:27:in `brew'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:112:in `<module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:18:in `<main>'
Error: Process completed with exit code 1.
```

When I ran it again (so this time the forked repository was already existing), it succeeded :

```
Switched to a new branch 'bump-archey4-4.13.1'
M	Formula/archey4.rb
[bump-archey4-4.13.1 971a38c1f1] archey4 4.13.1
 1 file changed, 2 insertions(+), 2 deletions(-)
remote: 
remote: Create a pull request for 'bump-archey4-4.13.1' on GitHub by visiting:        
remote:      HorlogeSkynet/homebrew-core/pull/new/bump-archey4-4.13.1        
remote: 
To HorlogeSkynet/homebrew-core.git
 * [new branch]            bump-archey4-4.13.1 -> bump-archey4-4.13.1
Branch 'bump-archey4-4.13.1' set up to track remote branch 'bump-archey4-4.13.1' from 'https://***@github.com/HorlogeSkynet/homebrew-core.git'.
```

---

Do you think it would be possible a race condition might occur while the repository is being forked ?

Thanks, bye :wave:

**Comment by dawidd6** [comment]
Relying on `brew` here to do the work and in it's source code we see:
https://github.com/Homebrew/brew/blob/fd46a173fef7a60bd7da5032f2fcde3c0ea0d1c2/Library/Homebrew/utils/github.rb#L451

that means it waits for 1 sec for GitHub to create a fork and this might be too quick I think.

**Comment by HorlogeSkynet** [comment]
Thanks for your feedback.
You're right, do we close here then ?
I don't mind rerunning failed jobs, but it maybe also means that we _should_ keep the Homebrew fork to mitigate this.

**Comment by dawidd6** [comment]
Yep, keep the forked repo, you shouldn't get this error anymore. One can't be sure to get the error you got every time the fork is created, sometimes it takes longer hence the error
