### ISSUE TITLE
Error: Query must include 'is:issue' or 'is:pull-request'

### ISSUE THREAD

**Issue by bartekpacia** [dawidd6/action-homebrew-bump-formula#48]
I'm trying to use this action to update formulas in my [personal tap](https://github.com/bartekpacia/homebrew-tools), but an error is preventing me from doing so.

Logs:

```
<omitted, installing bundler deps>
Bundle complete! 35 Gemfile dependencies, 77 gems now installed.
Bundled gems are installed into `../../../../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle`
Error: Query must include 'is:issue' or 'is:pull-request'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:323:in `safe_system': Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\([https://github.com/dawidd6/action-homebrew-bump-formula\](https://github.com/dawidd6/action-homebrew-bump-formula/)) --tag=v0.1.7 --revision=1cb39a47fd1735e6bc39ee5b4493b8c49bfe2780 bartekpacia/homebrew-tools/shell-scripts` exited with 1. (ErrorDuringExecution)
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:27:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:112:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:18:in `<main>'
Error: Process completed with exit code 1.
```

[Here's the link to my workflow](https://github.com/bartekpacia/shell-scripts/actions/workflows/bump-formula.yaml). I'd be very grateful for any help.

**Comment by bartekpacia** [comment]
It turned out to be a permission issue – I created a fine-grained token with insufficient permissions.

**Comment by dawidd6** [comment]
You have single quotes around tag, change to double quotes.

**Comment by bartekpacia** [comment]
Thanks, I fixed the quotes and now I'm getting:

```
<omitted>
Bundle complete! 35 Gemfile dependencies, 77 gems now installed.
Bundled gems are installed into `../../../../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle`
==> replace /tag:(\s+")0.1.6(?=")/ with "tag:\\10.2.0\\2"
Error: You need to bump this formula manually since the new version
and old version are both 0.1.6.
==> replace "bb6f32e44c852e481e2b62a6bd225ea10833fed2" with "f58d3a7c8a7a21a8b851c0c95c783451b601c0e5"
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:323:in `safe_system': Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\([https://github.com/dawidd6/action-homebrew-bump-formula\](https://github.com/dawidd6/action-homebrew-bump-formula/)) --tag=0.2.0 --revision=f58d3a7c8a7a21a8b851c0c95c783451b601c0e5 bartekpacia/homebrew-tools/shell-scripts` exited with 1. (ErrorDuringExecution)
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:27:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:112:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:18:in `<main>'
Error: Process completed with exit code 1.
```

Quite strange, I don't get why it's saying what it's saying, and I'm not very experienced with Homebrew. Again I'd be very happy to get some help :)
