### ISSUE TITLE
Error: undefined method `git_origin_branch' for #<Pathname:...>

### ISSUE THREAD

**Issue by slonopotamus** [dawidd6/action-homebrew-bump-formula#55]
I was happily using action-homebrew-bump-formula for several months (last successful run was [3 days ago](https://github.com/octobuild/octobuild/actions/runs/4697860416/jobs/8329432982#step:3:250)), until today it suddenly broke with

```
Bundled gems are installed into `../../../../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle`
Error: undefined method `git_origin_branch' for #<Pathname:0x0000558587649a80>
Do not report this issue until you've run `brew update` and tried again.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:126:in `bump_formula_pr'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:243:in `safe_system': Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\([https://github.com/dawidd6/action-homebrew-bump-formula\](https://github.com/dawidd6/action-homebrew-bump-formula/)) --version=0.6.0 octobuild` exited with 1. (ErrorDuringExecution)
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:26:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:105:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
```

https://github.com/octobuild/octobuild/actions/runs/4721924692/jobs/8375810652

Any thoughts how to fix this?

**Comment by dawidd6** [comment]
https://github.com/Homebrew/brew/pull/15246
