### ISSUE TITLE
Action cannot be used with GithHub app token

### ISSUE THREAD

**Issue by rfratto** [dawidd6/action-homebrew-bump-formula#66]
Our project has recently switched to use a GitHub app token for all of our GitHub actions that cross multiple repositories. However, the `/user` endpoint [does not work for GH app tokens](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28):

https://github.com/dawidd6/action-homebrew-bump-formula/blob/df6d545fcfd1ceb62b7e122933a8a4a0cf7eaba1/main.rb#L61

The action will always fail with:

```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github/api.rb:384:in `raise_error': GitHub API Error: Resource not accessible by integration (GitHub::API::AuthenticationFailedError)
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
  https://github.com/settings/tokens

	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github/api.rb:285:in `open_rest'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:61:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
```

**Comment by dawidd6** [comment]
Any suggestions how to resolve the issue?
